name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pyinstaller pyinstaller-versionfile
          $(if (Test-Path requirements.txt) { pip install -r requirements.txt })

      - name: Generate versionfile
        run: |
          create-version-file.exe versionfile.yaml --outfile versionfile

      - name: Build client executable
        run: |
          pyinstaller main.spec --clean

      - name: Build tool executables
        run: |
           pyinstaller scripts\get-active-window-title.py --onefile --distpath dist\tools --clean

      - name: Create release archive
        run: |
          Compress-Archive -Path "dist\0xQWERTY-client.exe","dist\tools\","config.example.yaml" -DestinationPath 0xQWERTY-client-${{ github.ref_name }}.zip

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: 0xQWERTY-client-${{ github.ref_name }}.zip
          draft: true
          generate_release_notes: true
          name: 0xQWERTY-client ${{ github.ref_name }}
          body: This is the ${{ github.ref_name }} release of the 0xQWERTY-client.
